# Site settings
title: Ioannis Stamatakis
description: Mechanical Engineer transitioning into Data Science
avatar: "https://avatars.githubusercontent.com/u/yourusername?v=4"
favicon: "/assets/img/favicon.ico"
baseurl: ""
url: "https://Ioannis-Stamatakis.github.io"

# Social media links (username only)
social-network-links:
  github: Ioannis-Stamatakis
  linkedin: stamioanni

# Beautiful Jekyll theme
remote_theme: daattali/beautiful-jekyll

# Navigation menu
navbar-links:
  About: "about"
  Portfolio: "portfolio"
  Contact: "contact"

# Author details
author:
  name: Ioannis Stamatakis
  bio: "Mechanical Engineer → Data Scientist"
  location: "Greece"

# Footer
footer-links-active:
  github: true
  linkedin: true
  email: false

# Build settings
markdown: kramdown
highlighter: rouge
timezone: Europe/Athens

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude
exclude:
  - CHANGELOG.md
  - CNAME
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - Vagrantfile

# Google Analytics
# google_analytics: "your-google-analytics-id"

# Comments
# disqus: "your-disqus-shortname" 