# Site settings
title: ""
description: ""
baseurl: ""
url: "https://Ioannis-Stamatakis.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-sitemap

# Minimal theme
theme: minima

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - README.md

# Social media links (username only)
social-network-links:
  github: Ioannis-Stamatakis
  linkedin: stamioanni

# Beautiful Jekyll theme
remote_theme: daattali/beautiful-jekyll

# Navigation menu
navbar-links:
  About: "about"

# Author details
author:
  name: Giannis Stamatakis
  bio: "Data Scientist"
  location: "Greece"

# Footer - completely disabled
footer-links-active:
  github: false
  linkedin: false
  email: false
  facebook: false
  twitter: false
  instagram: false

# Footer text
footer-text: ""
footer-extra: ""

# Hide default footer elements
show-avatar: false
show-footer: false

# Google Analytics
# google_analytics: "your-google-analytics-id"

# Comments
# disqus: "your-disqus-shortname" 